### ISSUE TITLE
`integrated.refl` shoeboxes are mostly zeros

### ISSUE THREAD

**Issue by kmdalton** [Hekstra-Lab/laue-index-assigner#20]
in the integration output, `integrated.refl`only about the first 800 shoeboxes have nonzero values

i used this snippet:

```python
refls = flex.reflection_table.from_file("dials_temp_files/integrated.refl")
nonzero = []
for i in range(len(refls)):
    data = refls['shoebox'][i].data.as_numpy_array()
    nonzero.append((data != 0).sum())
```
to count nonzero pixels in each shoebox. appears most of the shoeboxes are all zeros:

![image](https://user-images.githubusercontent.com/2790777/172513633-aa48e5ea-1568-4743-9f4a-a9afd425e250.png)

the intensities seem all good though. they merged just fine. i couldn't easily ascertain the source of this bug, but maybe you have some thoughts, @PrinceWalnut.

**Comment by PrinceWalnut** [comment]
This issue has to deal with the old DIALS integrator, which is now removed. The extra spots with shoeboxes of 0 are simply unrefined spots left in the reflection table.
