### ISSUE TITLE
new laue.sequence_to_stills from laue-dials 0.3 leads to spot predictions with high RMSDs

### ISSUE THREAD

**Issue by hkwang** [Hekstra-Lab/laue-index-assigner#25]
With laue-dials 0.3 and DIALS 3.17.0, `laue.sequence_to_stills` causes one of my passes to be misindexed, leading to spot predictions with RMSDs on the order of 15 pixels, from ~0.25 pixels, with a previous version of `laue.sequence_to_stills` (see DMs with Rick on the Hekstra lab Slack). I have attached a .yml file for the conda environment in which this spot prediction works.

**Comment by hkwang** [comment]
[env.yml.txt](https://github.com/Hekstra-Lab/laue-index-assigner/files/13591045/env.yml.txt)

**Comment by kmdalton** [comment]
should this be posted on the laue-dials repo or have i missed something important?

**Comment by PrinceWalnut** [comment]
Kevin is right here -- @hkwang please repost on the `laue-dials` repo. This repo is an old one that predated `laue-dials` -- we keep it for purposes of maintaining an archive of past work.
