### ISSUE TITLE
Does beam assignment per reflection really need filtration?

### ISSUE THREAD

**Issue by PrinceWalnut** [Hekstra-Lab/laue-index-assigner#3]
This process is the bottleneck on the speed of the beam assignment script, and leftover from when we were binning reflections to beams, and so some beams may get no reflections. Hypothetically, every beam here has precisely one reflection. Can we just cut filtration out entirely then, and speed it up?

**Comment by kmdalton** [comment]
this does not _need_ to be slow, it could easily be sped up. that being said, i think we should let dials.refine's outlier rejection do the filtration.

**Comment by PrinceWalnut** [comment]
Well I think the filtration is pointless in this case entirely. It had existed before because we were making wavelength bins that reflections may or may not fall in. Since we are now allocating beams per reflection, unless there are side effects that are important, I can throw away the filtration entirely, since no experiments will ever be filtered out. The original purpose was to make sure there were no empty experiments, which would break dials.refine.

**Comment by PrinceWalnut** [comment]
To be clear, it filters out experiments, not reflections. This isn't outlier rejection. I think it serves no purpose in this pipeline (stills->beam assignment instead of beam assignment -> stills)

**Comment by kmdalton** [comment]
copy that.

**Comment by PrinceWalnut** [comment]
Looked at the logic and saw nothing important, and just to be safe I `diff`ed the output files and there is no difference with or without filtration. Removed filtration and all attached functions in commit 6cf27e9b2b7a8c3de6b7e30baa7ca2710406f984.
