### ISSUE TITLE
Beams per reflection are all being given the same monochromatic wavelength

### ISSUE THREAD

**Issue by PrinceWalnut** [Hekstra-Lab/laue-index-assigner#4]
We need to ensure that wavelength data gets written into the refl file during miller optimization so that the beams are given different wavelengths. This is responsible for very large amounts of error.

**Comment by kmdalton** [comment]
they should refine really quickly to the correct values i would think.

**Comment by PrinceWalnut** [comment]
Just reopening this to keep it in my to-do.

**Comment by PrinceWalnut** [comment]
This issue is resolved by commit 6fbe6fa1e30074660526d65f4a14a1ce8737ad5c.
